// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('As variáveis de ambiente do Supabase não estão configuradas');
}

// Configurações otimizadas para evitar problemas de conexão em desenvolvimento
const supabaseOptions = {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 5, // Aumentado para permitir mais eventos por segundo
    },
    heartbeat: {
      interval: 8000, // Reduzido para 8 segundos para detectar desconexões mais rapidamente
      maxRetries: 10,   // Aumentado para mais tentativas de reconexão
    },
    reconnect: {
      delay: 1000,    // Espere 1 segundo para tentar reconectar
      maxRetries: 10,   // Aumentado para mais tentativas de reconexão
      timed: true,    // Escalonar o tempo de espera entre tentativas
    },
  },
  global: {
    fetch: fetch.bind(globalThis), // Usar o fetch global para evitar problemas em alguns browsers
    headers: {
      'X-Client-Info': 'comandeja-web',
    },
  },
  persistSession: true, // Persistir a sessão no localStorage
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, supabaseOptions);