// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqmbibkesypgqibfmoyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbWJpYmtlc3lwZ3FpYmZtb3lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDkwNzksImV4cCI6MjA2NDYyNTA3OX0.7xyW9g5vEQDsTGt5rXJ70okzPB7InD9KTtjjNJoyuaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);