// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('As variáveis de ambiente do Supabase não estão configuradas');
}

// Configurações otimizadas para evitar problemas de conexão em desenvolvimento
const supabaseOptions = {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 1, // Limite de eventos por segundo
    },
    heartbeat: {
      interval: 15000, // 15 segundos entre cada heartbeat
      maxRetries: 3,   // Número de tentativas de reconexão
    },
    reconnect: {
      delay: 1000,    // Espere 1 segundo para tentar reconectar
      maxRetries: 3,   // Máximo de 3 tentativas
      timed: false,    // Não escalone o tempo de espera
    },
  },
  global: {
    fetch: fetch.bind(globalThis), // Usar o fetch global para evitar problemas em alguns browsers
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, supabaseOptions);